import Header from "@/components/Header";
import { Session } from "next-auth";
import { getSession } from "next-auth/react";
import Head from "next/head";
import { useEffect, useState } from "react";
import { Container } from "react-bootstrap";


function Home() {
  const [isLoading, setIsLoading] = useState(true)
  const [loadedSession, setLoadedSession] = useState<null|Session>(null)
  

  useEffect(()=>{
    getSession().then(session=>{
      // setIsLoading(false)
      if(!session){
        window.location.href = '/auth'
      }else{
        setIsLoading(false)
      }
      setLoadedSession(session)
    })
  }, [])
  if(isLoading){
    return <>loading...</>
  }
  return (
    <>
      <Head>
        <title>Bootstrap w/ React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container as="main" className="py-4 px-3 mx-auto">
        <Header />
      </Container>
    </>
  );
}

export default Home
